# This is a basic workflow to help you get started with Actions

name: CI-CD-for-Anya
env:
  EB_PACKAGE_S3      : "gitanya"
  EB_APPLICATION_NAME: "kotik"
  EB_ENVIROMENT_NAME : "kotik-env"
  DEPLOY_PACKAGE_NAME: "kotik_app_${{ github.sha }}.zip"
  
on:
  push:
    branches:
      - master

 
  workflow_dispatch:

 
jobs:
  my_ci_step:
    runs-on: ubuntu-latest
 
    steps: 
      - name: Git CI
        uses: actions/checkout@v2
  

      - name: zip
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
